const ProjectData = [
  {
    Id: "1",
    Name: "Accordian_App",
    Description:
      "This is a basic accordian or a questions app, multiselection added ",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/accordion",
    ImageSrc: "./accordion.png",
  },
  {
    Id: "2",
    Name: "Color_generator",
    Description:
      "This is a basic color generator app that generates hex or rgb colors",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/colorGenerator",
    ImageSrc: "./random_color_generator.png",
  },
  {
    Id: "3",
    Name: "Star_Rating",
    Description: "This app allows user to assign rating",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/starRating",
    ImageSrc: "./star_rating.png",
  },
  {
    Id: "4",
    Name: "Image Slider",
    Description: "This app illustrate a image slider to view multiple images",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/imageSlider",
    ImageSrc: "./image-slider.png",
  },
  {
    Id: "5",
    Name: "Load More Products",
    Description: "This app illustrate how data is fetched from a api",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/loadProducts",
    ImageSrc: "./load-more-products.png",
  },
  {
    Id: "6",
    Name: "Tree View",
    Description:
      "This app illustrate the side bar tree view and its functionalities",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/treeView",
    ImageSrc: "./tree-view.png",
  },
  {
    Id: "7",
    Name: "QR Code Generator",
    Description:
      "This app generate a qr code on the text which is given by user",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/qrgenerator",
    ImageSrc: "./qr-code-gen.png",
  },
  {
    Id: "8",
    Name: "Light Dark Mode",
    Description: "This app explains the theme switch",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/lightdarkmode",
    ImageSrc: "./theme-change.png",
  },
  {
    Id: "9",
    Name: "Scroll Bar",
    Description:
      "This app is designed to show a scroll bar progress on the top as we scroll the window",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/scrollbar",
    ImageSrc: "./scroll-bar.png",
  },
  {
    Id: "10",
    Name: "Tabs",
    Description:
      "This app illustrates the function of tabs and how they are implemented",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/tabs",
    ImageSrc: "./tabs.png",
  },
  {
    Id: "11",
    Name: "Modal Page",
    Description: "This app represent a basic modal page",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/modalpage",
    ImageSrc: "./modal-page.png",
  },
  {
    Id: "12",
    Name: "GitHub Profile Finder",
    Description:
      "This app helps to get user details when user name is given using github api",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/githubfinder",
    ImageSrc: "./githubfinder.png",
  },
  {
    Id: "13",
    Name: "Search User",
    Description: "This app helps to get user name auto complete",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/searchuser",
    ImageSrc: "./searchuser.png",
  },
  {
    Id: "14",
    Name: "Tic Tac Toe Game",
    Description: "This app is a tic tac toe game",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/tictactoegame",
    ImageSrc: "./tictacgame.png",
  },
  {
    Id: "15",
    Name: "Feature Flags",
    Description:
      "This apps uses context concept to display multiple components",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/featureflags",
    ImageSrc: "./featureflag.png",
  },

  {
    Id: "16",
    Name: "Custom hooks",
    Description: "This apps illustrates how a custom fetch is created",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/customhooks",
    ImageSrc: "./custom-hooks.png",
  },
  {
    Id: "17",
    Name: "Scroll Top Bottom Buttons",
    Description: "This apps illustrates how a custom fetch is created",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/scrolltopbottom",
    ImageSrc: "./scrolltopbottom.png",
  },
  {
    Id: "18",
    Name: "Scroll To Section",
    Description: "This apps illustrates how a custom fetch is created",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/scrolltosection",
    ImageSrc: "./scrolltosection.png",
  },
  {
    Id: "19",
    Name: "Weather App",
    Description: "This apps illustrates how a custom fetch is created",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/weatherapp",
    ImageSrc: "./weatherapp.png",
  },
  {
    Id: "20",
    Name: "Expense Tracker",
    Description: "This apps illustrates how a custom fetch is created",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/expensetracker",
    ImageSrc: "./expensetracker.png",
  },
  {
    Id: "21",
    Name: "Social App",
    Description: "This apps illustrates how a custom fetch is created",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/socialmediaapp",
    ImageSrc: "./socialmedia.png",
  },
  {
    Id: "22",
    Name: "Todo List App",
    Description: "This apps illustrates how a custom fetch is created",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/todolistapp",
    ImageSrc: "./todolist.png",
  },
];
export default ProjectData;
