const ProjectData = [
  {
    Id: "1",
    Name: "Accordian_App",
    Description:
      "This is a basic accordian or a questions app, multiselection added ",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/accordion",
    ImageSrc: "./accordion.png",
  },
  {
    Id: "2",
    Name: "Color_generator",
    Description:
      "This is a basiccolor generator app that generates hex or rgb colors",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/colorGenerator",
    ImageSrc: "./random_color_generator.png",
  },
  {
    Id: "3",
    Name: "Star_Rating",
    Description:
      "This is a basiccolor generator app that generates hex or rgb colors",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/starRating",
    ImageSrc: "./star_rating.png",
  },
  {
    Id: "4",
    Name: "Image Slider",
    Description:
      "This is a basiccolor generator app that generates hex or rgb colors",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/imageSlider",
    ImageSrc: "./image-slider.png",
  },
  {
    Id: "5",
    Name: "Load More Products",
    Description:
      "This is a basiccolor generator app that generates hex or rgb colors",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/loadProducts",
    ImageSrc: "./load-more-products.png",
  },
  {
    Id: "6",
    Name: "Tree View",
    Description:
      "This is a basiccolor generator app that generates hex or rgb colors",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/treeView",
    ImageSrc: "./tree-view.png",
  },
  {
    Id: "7",
    Name: "QR Code Generator",
    Description:
      "This is a basiccolor generator app that generates hex or rgb colors",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/qrgenerator",
    ImageSrc: "./qr-code-gen.png",
  },
  {
    Id: "8",
    Name: "Light Dark Mode",
    Description:
      "This is a basiccolor generator app that generates hex or rgb colors",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/lightdarkmode",
    ImageSrc: "./theme-change.png",
  },
  {
    Id: "9",
    Name: "Scroll Bar",
    Description:
      "This is a basiccolor generator app that generates hex or rgb colors",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/scrollbar",
    ImageSrc: "./scroll-bar.png",
  },
  {
    Id: "10",
    Name: "Tabs",
    Description:
      "This is a basiccolor generator app that generates hex or rgb colors",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/tabs",
    ImageSrc: "./tabs.png",
  },
  {
    Id: "11",
    Name: "Modal Page",
    Description:
      "This is a basiccolor generator app that generates hex or rgb colors",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/modalpage",
    ImageSrc: "./modal-page.png",
  },
  {
    Id: "12",
    Name: "GitHub Profile Finder",
    Description: "This app helps to get user details when user name is given",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/githubfinder",
    ImageSrc: "./githubfinder.png",
  },
  {
    Id: "13",
    Name: "Search User",
    Description: "This app helps to get user details when user name is given",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/searchuser",
    ImageSrc: "./searchuser.png",
  },
  {
    Id: "14",
    Name: "Tic Tac Toe Game",
    Description: "This app helps to get user details when user name is given",
    Languages: ["Html", "Css", "Javascript", "React js"],
    Frameworks: "Bootstrap",
    Concepts: "routing",
    Link: "/tictactoegame",
    ImageSrc: "./searchuser.png",
  },
];
export default ProjectData;
